openapi: 3.0.2
info:
  title: Image Tree
  description: Construct image num-tree.
  version: 1.0.0

paths:
  /tree:
    get:
      description: Construct image num-tree.
      operationId: main.create_tree
      responses:
        200:
          description: Successfully
  /:
    get:
      description: create app.
      operationId: main.create_app
      responses:
        200:
          description: Successfully
    post:
      description: upload file.
      operationId: main.upload_and_create_tree
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: [ 'txtFile', 'countNodes' ]
              properties:
                txtFile:
                  type: string
                  format: binary
                countNodes:
                  type: string
      responses:
        200:
          description: File uploaded successfully
          content:
            'application/json':
              schema:
                type: object
                properties:
                  message:
                    type: string
